version: "3.8"
services:
  vpn_proxy:
    image: ghcr.io/michaeljones32/pia-openvpn-proxy
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VPN_PROXY_CONFIG}:/config
    # if using wireguard, uncomment the next line
    #privileged: true
    environment:
      - VPN_PROTOCOL=${VPN_PROTOCOL}
      - REGION=${REGION}
      - USERNAME=${PIA_USERNAME}
      - PASSWORD=${PIA_PASSWORD}
      - UID=${UID}
      - GID=${GID}
      - LOCAL_NETWORK=${LOCAL_NET}/24
    networks:
      - vpn_proxy
    ports:
      - 8118:8118
    restart: always

networks:
  vpn_proxy:
